services:
  ollama:
    image: ollama/ollama:latest
    restart: always
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    # Use entrypoint to start ollama serve directly
    entrypoint: ["/bin/bash", "-c"]
    # Command to run after service starts
    command: >
      "ollama serve & sleep 10 &&
       ollama pull nomic-embed-text &&
       tail -f /dev/null"

volumes:
  ollama:
    driver: local
